import {describe,it,expect,vi} from 'vitest';import {EventEmitter} from 'node:events';
import {UpdateController} from '../electron/updater';
class Fake extends EventEmitter{autoDownload=true;autoInstallOnAppQuit=true;allowPrerelease=true;allowDowngrade=true;checkForUpdates=vi.fn(async()=>{});downloadUpdate=vi.fn(async()=>{});quitAndInstall=vi.fn();}
describe('업데이트 확인과 설치',()=>{
 it('no automatic download or app-quit installation, prompts available and ready',async()=>{const a=new Fake(),show=vi.fn(),prepare=vi.fn();const c=new UpdateController(a,'1.0.0',true,()=>{},show,prepare,()=>{});expect(a.autoDownload).toBe(false);expect(a.autoInstallOnAppQuit).toBe(false);await c.check();expect(a.checkForUpdates).toHaveBeenCalledOnce();a.emit('update-available',{version:'1.1.0'});expect(c.state.status).toBe('available');expect(show).toHaveBeenCalledOnce();await c.download();expect(a.downloadUpdate).toHaveBeenCalledOnce();a.emit('download-progress',{percent:41.5});expect(c.state.percent).toBe(42);expect(()=>c.install()).toThrow();a.emit('update-downloaded',{version:'1.1.0'});expect(show).toHaveBeenCalledTimes(2);c.install();expect(prepare).toHaveBeenCalledOnce();expect(a.quitAndInstall).toHaveBeenCalledWith(true,true);});
 it('offline errors recover and development mode never checks',async()=>{const a=new Fake();a.checkForUpdates.mockRejectedValueOnce(new Error('offline'));const c=new UpdateController(a,'1.0.0',true,()=>{},()=>{},()=>{},()=>{});await c.check();expect(c.state.status).toBe('error');await c.check();expect(a.checkForUpdates).toHaveBeenCalledTimes(2);const disabled=new UpdateController(new Fake(),'1.0.0',false,()=>{},()=>{},()=>{},()=>{});await disabled.check();expect(disabled.state.status).toBe('disabled');});
 it('save failure prevents installation',()=>{const a=new Fake(),c=new UpdateController(a,'1.0.0',true,()=>{},()=>{},()=>{throw new Error('disk full');},()=>{});a.emit('update-downloaded',{version:'1.1.0'});expect(()=>c.install()).toThrow('disk full');expect(a.quitAndInstall).not.toHaveBeenCalled();});
 it('failed install restores error instead of trapping installing',()=>{const a=new Fake(),c=new UpdateController(a,'1.0.0',true,()=>{},()=>{},()=>{},()=>{});a.emit('update-downloaded',{version:'1.1.0'});a.quitAndInstall.mockImplementation(()=>{throw new Error('installer unavailable');});expect(()=>c.install()).toThrow('installer unavailable');expect(c.state.status).toBe('error');});
});
