import {_electron as electron} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const dir=path.resolve('test-results','appearance-data');await fs.mkdir(dir,{recursive:true});let app;
try{
 app=await electron.launch({...(process.env.OVERTIME_EXE?{executablePath:process.env.OVERTIME_EXE}:{}),args:process.env.OVERTIME_EXE?[]:['.'],env:{...process.env,OVERTIME_DATA_DIR:dir}});const page=await app.firstWindow();await page.getByRole('heading',{name:'초과근무',exact:true}).waitFor();await page.evaluate(()=>window.overtime.command({type:'settings',onboarded:true,sound:false}));await page.getByRole('button',{name:'설정',exact:true}).click();await page.getByRole('heading',{name:/앱 업데이트.*@2026 j.u.Eun/}).waitFor();
 await page.evaluate(async()=>{await document.fonts.load('14px "Noto Sans KR Variable"','초과근무 나이스');await document.fonts.ready;});const family=await page.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily);assert.ok(family.includes('Noto Sans KR Variable'));assert.equal(await page.getByText(/인사랑/).count(),0);assert.ok(await page.getByText(/나이스/).count()>0);
 assert.equal(await page.getByText(/GitHub Releases|GitHub/).count(),0);
 const client=await page.context().newCDPSession(page);await client.send('DOM.enable');await client.send('CSS.enable');const {root}=await client.send('DOM.getDocument');const {nodeId}=await client.send('DOM.querySelector',{nodeId:root.nodeId,selector:'h1'});const {fonts}=await client.send('CSS.getPlatformFontsForNode',{nodeId});assert.ok(fonts.some(f=>f.isCustomFont&&/Noto/i.test(f.familyName)),'Korean heading must render bundled Noto font, not a system fallback');await page.locator('.content').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'test-results/settings-final.png'});
 const result={result:'PASS',family,fonts,credit:'@2026 j.u.Eun',copy:'나이스',screenshot:'settings-final.png'};await fs.writeFile('test-results/appearance-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{if(app)await app.close();}
